### ISSUE TITLE
Fix version tag 

### ISSUE THREAD

**Issue by 89z** [otaviokr/topological-sort#10]
Current tag is 1.1.0:

https://github.com/otaviokr/topological-sort/releases/tag/1.1.0

However this format of tag is not valid for Go modules. Proper format would be:

~~~
v1.1.0
~~~

because of this, importing `topological-sort` looks like this:

~~~
require github.com/otaviokr/topological-sort v0.0.0-20210425205821-07838e2042aa
~~~

and the documentation shows no tagged version is available:

https://pkg.go.dev/github.com/otaviokr/topological-sort

**Comment by otaviokr** [comment]
Hi @89z 
Thanks for the info - I've never noticed that.
The tag is fixed.
